# Use Tomcat as the base image
FROM tomcat:9-jdk11-openjdk

# Set the maintainer label (optional)
LABEL maintainer="tohidhanfi.com"

# Copy the WAR file generated by Maven into Tomcat's webapps directory
COPY target/my-app.war /usr/local/tomcat/webapps/

# Expose the port Tomcat will be running on
EXPOSE 8082

# Start Tomcat when the container runs
CMD ["catalina.sh", "run"]
