# Use Tomcat as the base image
FROM tomcat:9-jdk11-openjdk

# Set the maintainer label (optional)
LABEL maintainer="tohidhanfi.com"

# Copy the WAR file generated by Maven into Tomcat's webapps directory
COPY ./web-app.war /usr/local/tomcat/webapps
